### references
https://kogler.wordpress.com/2008/03/21/latex-multiline-equations-systems-and-matrices/ 

http://apmonitor.com/che263/index.php/Main/PythonSolveEquations

http://janroman.dhis.org/finance/Bootstrap%20Yield-Fitting/Munk_Yield.pdf

https://sisweb.tesouro.gov.br/apex/f?p=2031:2:0::::

In [1]:
import numpy as np

In [5]:
A = [90, 98]
B = [[5, 105], [58, 54]]

AM = np.matrix(A)
BM = np.matrix(B)

In [18]:
print(AM)
print(BM)


[[90 98]]
[[  5 105]
 [ 58  54]]


In [15]:
BM * AM.T

matrix([[10740],
        [10512]])

In [17]:
# print((90 * 5) + (98 * 58))
# print((90 * 105) +(98 * 54))
print((5 * 90) + (105 * 98))
print((58 * 90) + (54 * 98))

10740
10512


In [22]:
print(np.dot(A, B))
print(AM*BM)

print(np.dot(B, A))
print(BM*AM.T)

[ 6134 14742]
[[ 6134 14742]]
[10740 10512]
[[10740]
 [10512]]


## How to use find the inverse of a matrix

In [25]:
inverse = np.linalg.inv(A)
inverse

matrix([[ 0.   ,  0.5  ],
        [ 0.25 , -0.125]])

## How to find the <font color='red'>eigenvalues</font> of a matrix


In [26]:
eigvals = np.linalg.eigvals(A)
eigvals

array([ 3.37228132, -2.37228132])

## How to find the associated <font color='red'>eigenvectors</font> of a matrix


In [28]:
eigvec = np.linalg.eigh(A)
eigvec

(array([-1.56155281,  2.56155281]), matrix([[ 0.61541221, -0.78820544],
         [-0.78820544, -0.61541221]]))

## Singular Value Decomposition

In [29]:
svd = np.linalg.svd(matrix)
svd

(matrix([[-0.98888296, -0.14869598],
         [-0.14869598,  0.98888296]]),
 array([ 4.15941525,  1.92334728]),
 matrix([[-0.30924417, -0.95098267],
         [ 0.95098267, -0.30924417]]))

## Source Code for Linear Solutions


\begin{equation*}
A * z = b\\
\begin{bmatrix}
    3 & -9\\
    2 & 4\\
\end{bmatrix} * \begin{bmatrix}
                        z_{1}\\
                        z_{2}\\
                    \end{bmatrix} = \begin{bmatrix}
                                        -42\\
                                        2\\
                                     \end{bmatrix}                                        
\end{equation*}

In [34]:
A = np.array([ [3,-9], [2,4] ])
b = np.array([-42,2])
z = np.linalg.solve(A,b)
print(z)

[-5.  3.]


\begin{equation*}
M * y = c\\
\begin{bmatrix}
    1 & -1 & -1\\
    2 & 2 & -1\\
    -1 & -1 & 2\\
\end{bmatrix} * \begin{bmatrix}
                        y_{1}\\
                        y_{2}\\
                        y_{3}\\
                    \end{bmatrix} = \begin{bmatrix}
                                        -6\\
                                        1\\
                                        1\\
                                     \end{bmatrix}                                        
\end{equation*}

In [32]:
M = np.array([ [1,-2,-1], [2,2,-1], [-1,-1,2] ])
c = np.array([6,1,1])
y = np.linalg.solve(M,c)
print(y)

[ 3. -2.  1.]


## Solve Nonlinear Equations with Python


\begin{equation}
    \begin{cases}
        x^{2} + y^{2} = 20\\
        y - x^{2} = 0\\
        w - x*y = -5\\
    \end{cases} = 
    \begin{cases}
        x^{2} + y^{2} - 20 = 0\\
        y - x^{2} + 0 = 0\\
        w - x*y + 5 = 0\\
    \end{cases}
\end{equation}

In [35]:
from scipy.optimize import *

In [39]:
def myFunction(z):
   x = z[0]
   y = z[1]
   w = z[2]

   F = np.empty((len(z)))
   F[0] = pow(x,2)+pow(y,2)-20
   F[1] = y - pow(x,2)
   F[2] = w + 5 - x*y
   return F

zGuess = np.array([1,1,1])
z = fsolve(myFunction,zGuess)
print(z)

[ 2.  4.  3.]
